---
docker:
  user: ubuntu
  groups:
  - docker
  docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
  docker_deps:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - apt-utils

optional_tasks:
  setup_compose: true
  setup_docker_zfs: true
  zpool_name: storage
  compose_basedir: docker
  compose_file_dirs:
  - media_stack
  - timemachine_backups