---
docker:
  user: ubuntu
  groups:
  - docker
  docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
  docker_deps:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - apt-utils

additional_packages:
- unrar

optional_tasks:
  setup_compose: true
  setup_docker_zfs: true
  zpool_name: storage
  compose_basedir: docker
  compose_file_dirs:
  - media_stack
  - media_stack/radarr
  - media_stack/sonarr
  - media_stack/jackett
  - media_stack/data
  - media_stack/data/tv
  - media_stack/data/movies
  - media_stack/data/music
  - media_stack/data/downloads
  - media_stack/plex
  - media_stack/ombi
  - media_stack/transmission
  - media_stack/tautulli
  - media_stack/tautulli/logs
  - media_stack/tautulli/config
  compose_file:
    composeVersion: "3.7"
    restartPolicy: unless-stopped
    containers:
      radarr:
        enabled: true
        memoryLimit: 1G
      sonarr:
        enabled: true
        memoryLimit: 1G
      jackett:
        enabled: true
        memoryLimit: 1G
      transmission:
        enabled: true
        memoryLimit: 1G
        flood:
          enabled: true
      plex:
        enabled: true
        memoryLimit: 12G
        tautulli:
          enabled: true
          memoryLimit: 1G
      ombi:
        enabled: false
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/Chicago"
