---
- name: "Configure media server"
  gather_facts: yes
  hosts: media
  vars_files:
    - group_vars/all.yaml
    - group_vars/plex.yaml
  tasks:
    - assert:
        that:
        - "ansible_distribution == 'Ubuntu'"
        fail_msg: "This playbook contains apt specific tasks that will not work on non-Ubuntu systems"
    - import_tasks: tasks/base.yaml
    - import_tasks: tasks/docker.yaml
    - import_tasks: tasks/media.yaml
      when: optional_tasks.setup_compose is true